// Mouth package for: character
// Generated by Alien Lip Sync app
// Usage: include this file, then call window.characterMouthStart() / window.characterMouthStop()

const CHARACTER_MOUTH = {
  // Position as fraction of sprite (0-1). Multiply by your sprite's pixel size to position.
  cx: 0.5033,   // horizontal centre
  cy: 0.1612,   // vertical centre
  w:  0.0473,   // width fraction
  h:  0.0127,   // height fraction
  // Mouth style settings at time of export
  curve: 0.850,
  widthScale: 1.000,
  openScale: 1.100,
  color: '#2a2a2a',
  radius: 0.240,
  // Base64 mouth crop image
  crop: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABYAAAAHCAYAAAAMPr0FAAACEElEQVR4ARyRvU8TcRjHP722R8tLOWiBWmN4KUVAothEdBDjgIsursa4GFw0MVFjYuLggonRyQVnExddjImLm/+EKxBKe23v/UoL9F5+Xm/4Js/zHb7fT55HenDnpri/eV3c3bgmtqrr4taVZbGxPCtur1XEvfUV8WRrU3zcfih2nz0Wu08fia+vtsWPd8/Fz50X4ven17F+fXgp/nx+I/5+eSv+fdsR+9/fC8nzArrdLpZj0zZ03OMOvV4P13VxLJvGUZ2DvX2ObQfh+biR126oaGoTS9MxdB3bMrAMk0atgaq26PZOkQYhjuMw0CDMsiw6ncFuRZ6F1lKpHxyiNo7iMNc0sVot9KZKq1GnVathRCWDosO9A5pqOwI9QXJdG8/z8H0/Mjr0+2cIIUilUuRyORbm51goz1GanuJCscjSfJmra5fZWK+yWq5wcW6elfICpYk82XQKTTPQDBspCAKCwEdKCDJpGVmWyWRklNwo01N5isVpZgp5FCXHhDLOVGEyLpk9X2IpCl1dXORSpRKVrXCjWqUwmSeZkpHC0I8J0+kk48oYueEsI0MZMnI6VkKE0c06EUmber1Gu3mErjVxHZOwf0JaCpGBbDKBMjrCudJMDCelJIkEIamkxNjwMNmINhoJfS860Rl975ST7jF2FGSYGpqpY1rt6A8WfnBKUhKx5CSMZGUKEwqZoTT/AQAA//+6pM/IAAAABklEQVQDANvhEbEAqE9rAAAAAElFTkSuQmCC',
  // Amplitude data — 30fps, 160 frames
  data: [0.048,0.202,0.759,0.818,0.939,0.981,0.962,0.869,0.873,0.955,0.839,0.937,0.754,0.241,0.481,0.914,0.892,0.836,0.943,0.809,0.657,0.232,0.707,0.951,0.905,0.79,0.64,0.243,0.145,0.179,0.863,0.977,0.859,0.859,0.721,0.703,0.797,0.949,0.895,0.663,0.475,0.645,0.644,0.677,0.249,0.222,0.6,0.933,0.675,0.298,0.15,0.649,0.931,0.635,0.35,0.435,0.169,0.132,0.121,0.75,0.928,0.931,0.962,0.916,0.817,0.916,0.669,0.783,0.723,0.753,0.639,0.649,0.406,0.271,0.276,0.226,0.144,0.713,0.58,0.93,0.865,0.955,0.951,0.776,0.686,0.584,0.634,0.287,0.581,0.707,0.891,0.714,0.598,0.214,0.399,0.316,0.284,0.358,0.462,0.372,0.895,0.964,0.989,0.884,0.446,0.241,0.24,0.154,0.816,0.63,0.704,0.917,0.918,0.91,0.717,0.748,0.786,0.38,0.176,0.581,0.766,0.961,0.967,0.921,0.956,0.955,0.355,0.225,0.172,0.459,0.777,0.963,0.845,0.922,0.63,0.23,0.168,0.147,0.525,0.608,0.492,0.846,0.954,0.947,0.984,0.714,0.78,0.855,0.635,0.439,0.827,0.815,0.876,0.47,0.18,0.531,0.254,0.153,0.136,0.128],
  interval: 33
};
